### ISSUE TITLE
Chrome/Opera potential out of memory crash

### ISSUE THREAD

**Issue by frumbert** [kentmw/jpeg-web-worker#1]
_When DevTools is open_ in Opera or Chrome and a large (several MB) image is being handled, I often get a "Paused before potential out-of-memory crash". You can step over them and it all works, but I wonder why it thinks it's about to run out of memory. I catch inside `processDU` where it's walking backwards over DU to zero it (encode ac's). It also falls flat at `function writeBits(bs)` performing `while(posval >=0)`.

**Comment by kentmw** [comment]
Seems like something about the Chrome debugger. The mapbox team seemed to encounter the same thing for their project - they decided that because it didn't affect anything after clicking continue, that it wasn't a bug. They also notified the Google team. See https://github.com/mapbox/mapbox-gl-js/issues/4330

**Comment by frumbert** [comment]
Hmm, I guess it's a "wait and see" then. Cheers!
